var clubs = [
    {'id':'1', 'area': '08', 'name': 'Rotary E-Club of Tamar Hong Kong'},
    {'id':'2', 'area': '06', 'name': 'Rotary Club of Tolo Harbour'},
    {'id':'3', 'area': '06', 'name': 'Rotary Club of Hong Kong Sunrise'},
    {'id':'4', 'area': '06', 'name': 'Rotary Club of Shatin'},
    {'id':'5', 'area': '04', 'name': 'Rotary Club of SoHo Hong Kong'},
    {'id':'6', 'area': '06', 'name': 'Rotary Club of Guangdong-HK-Macau Greater Bay Area'},
    {'id':'7', 'area': '05', 'name': 'Rotary Club of The Peak'},
    {'id':'8', 'area': '08', 'name': 'Rotary Club of Manhattan Hong kong'},
    {'id':'9', 'area': '01', 'name': 'Rotary Club of Guia'},
    {'id':'10', 'area': '02', 'name': 'Rotary Club of Wanchai'},
    {'id':'11', 'area': '01', 'name': 'Rotary Club of Hou Kuong'},
    {'id':'12', 'area': '07', 'name': 'Rotary Club of Peninsula South'},
    {'id':'13', 'area': '06', 'name': 'Rotary Club of Mandarin Hong Kong'},
    {'id':'14', 'area': '03', 'name': 'Rotary Club of Hong Kong Northeast'},
    {'id':'15', 'area': '05', 'name': 'Rotary Club of Green Hong Kong'},
    {'id':'16', 'area': '04', 'name': 'Rotary Club of Lan Kwai Fong'},
    {'id':'17', 'area': '01', 'name': 'Rotary Club of Oriental Pearl Macau'},
    {'id':'18', 'area': '06', 'name': 'Rotary Club of New Territories'},
    {'id':'19', 'area': '11', 'name': 'Rotary Club of Metropolitan Hong Kong'},
    {'id':'20', 'area': '06', 'name': 'Rotary Club of Kwai Chung'},
    {'id':'21', 'area': '01', 'name': 'Rotary Club of Penha Macao'},
    {'id':'22', 'area': '03', 'name': 'Rotary Club of Hong Kong Harbour'},
    {'id':'23', 'area': '06', 'name': 'Rotary Satellite Club of Tolo Harbour - Happy Health'},
    {'id':'24', 'area': '02', 'name': 'Rotary Club of Hong Kong'},
    {'id':'25', 'area': '05', 'name': 'Rotary Club of Mid-level'},
    {'id':'26', 'area': '11', 'name': 'Rotary Club of Neoteric Hong Kong'},
    {'id':'27', 'area': '01', 'name': 'Rotary Club of Macau'},
    {'id':'28', 'area': '02', 'name': 'Rotary Club of Innovation Hong Kong'},
    {'id':'29', 'area': '07', 'name': 'Rotary Club of Peninsula'},
    {'id':'30', 'area': '01', 'name': 'Rotary Club of Macau Central'},
    {'id':'31', 'area': '01', 'name': 'Rotary Club of Amizade Macau'},
    {'id':'32', 'area': '03', 'name': 'Rotary Club of Hong Kong Island East'},
    {'id':'33', 'area': '04', 'name': 'Rotary Club of Bayview Sunshine Hong Kong'},
    {'id':'34', 'area': '07', 'name': 'Rotary Club of Dragon Hong Kong'},
    {'id':'35', 'area': '12', 'name': 'Rotary Club of Kowloon East'},
    {'id':'36', 'area': '12', 'name': 'Rotary Club of Kingspark Hong Kong'},
    {'id':'37', 'area': '08', 'name': 'Rotary Club of Greater Bay Area'},
    {'id':'38', 'area': '11', 'name': 'Rotary Club of Abacus Hong Kong'},
    {'id':'39', 'area': '02', 'name': 'Rotary Club of Admiralty'},
    {'id':'40', 'area': '07', 'name': 'Rotary Club of Tsim Sha Tsui'},
    {'id':'41', 'area': '04', 'name': 'Rotary Club of Hong Kong City North'},
    {'id':'42', 'area': '04', 'name': 'Rotary Club of Hong Kong North'},
    {'id':'43', 'area': '07', 'name': 'Rotary Club of Elite-Orient'},
    {'id':'44', 'area': '02', 'name': 'Rotary Club of Smart Hong Kong'},
    {'id':'45', 'area': '11', 'name': 'Rotary Club of Ability Hong Kong'},
    {'id':'46', 'area': '06', 'name': 'Rotary Club of Tsuen Wan'},
    {'id':'47', 'area': '08', 'name': 'Rotary E-Club of District 3450'},
    {'id':'48', 'area': '08', 'name': 'Rotary Club of Kowloon Tong'},
    {'id':'49', 'area': '04', 'name': 'Rotary Club of Causeway Bay'},
    {'id':'50', 'area': '04', 'name': 'Rotary Club of Star Avenue'},
    {'id':'51', 'area': '05', 'name': 'Rotary Club of Golden Bauhinia Hong Kong'},
    {'id':'52', 'area': '12', 'name': 'Rotary Club of Kowloon Northeast'},
    {'id':'53', 'area': '00', 'name': 'RAGFP Hong Kong & Macao Chapter'},
    {'id':'54', 'area': '03', 'name': 'Rotary Club of The HUB Hong Kong'},
    {'id':'55', 'area': '07', 'name': 'Rotary Club of Kai Tak'},
    {'id':'56', 'area': '06', 'name': 'Rotary Club of Channel Islands'},
    {'id':'57', 'area': '02', 'name': 'Rotary Club of Queensway'},
    {'id':'58', 'area': '11', 'name': 'Rotary Club of Island Green'},
    {'id':'59', 'area': '06', 'name': 'Rotary Club of Tai-Po'}
];